# ========================================================
# ROL: FIREWALL PARA VM del DIINF
# Descripción: Configura el firewall UFW para el DIINF, permitiendo solo puertos HTTP/HTTPS
# ========================================================
---
# Instalación de UFW
- name: Asegurar que UFW esté instalado
  apt:
    name: ufw
    state: present
    update_cache: yes
  become: true

# Permitir HTTP/HTTPS (puertos 80,443)
- name: Permitir tráfico HTTP (puerto 80) y HTTPS (puerto 443)
  command: ufw allow proto tcp from any to any port 80,443
  become: true

# Habilitar el firewall
- name: Habilitar UFW
  command: ufw --force enable
  become: true

# Verificar y mostrar el estado del firewall
- name: Verificar configuración del Firewall
  command: ufw status
  register: ufw_status
  changed_when: false
  become: true

# Mostrar la configuración para verificación
- name: Mostrar estado del Firewall
  debug:
    var: ufw_status.stdout
