---
# =====================================
# ROL: PYTHON
# Descripción: Instala Python y dependencias necesarias para Docker y gestión de contenedores
# =====================================

# Instalar Python 3
- name: Asegurar que Python 3 esté instalado
  apt:
    name: python3
    state: present
    update_cache: yes
  become: true

# Instalar pip3 para gestión de paquetes Python
- name: Asegurar que pip3 esté instalado
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: true

- name: Remove old virtual environment (if needed)
  file:
    path: /opt/vitrina_venv
    state: absent
  become: true

- name: Create virtualenv with Python 3.10
  command: python3.10 -m venv /opt/vitrina_venv
  become: true


- name: Install required build tools and Python headers
  apt:
    name:
      - build-essential
      - python3-dev
      - libffi-dev
      - libssl-dev
    state: present
  become: true

- name: Install PyYAML manually first to avoid wheel build error
  pip:
    name: PyYAML==6.0
    virtualenv: /opt/vitrina_venv
  become: true

- name: Instalar dependencias Python necesarias
  pip:
    name:
      - docker==6.1.3
      - requests==2.28.2
      - urllib3==1.26.20
      - requests_unixsocket
    virtualenv: /opt/vitrina_venv

