---
# =====================================
# ROL: PYTHON
# Descripción: Instala Python y dependencias necesarias para Docker y gestión de contenedores
# =====================================

# Instalar Python 3
- name: Asegurar que Python 3 esté instalado
  apt:
    name: python3
    state: present
    update_cache: yes
  become: true

# Instalar pip3 para gestión de paquetes Python
- name: Asegurar que pip3 esté instalado
  apt:
    name: python3-pip
    state: present
    update_cache: yes
  become: true

# Instalar dependencias específicas de Python
# NOTA: Puedes modificar esta lista según las necesidades del proyecto (ya tiene versiones compatibles)
- name: Instalar dependencias Python necesarias
  pip:
    name:
      - docker==6.1.3         # SDK de Docker para Python
      - docker-compose==1.29.2 # Versión compatible con el plugin docker-compose
      - requests==2.28.2      # Librería para realizar peticiones HTTP
      - urllib3==1.26.20      # Dependencia de requests
      - requests_unixsocket   # Para comunicarse con sockets Unix
    executable: pip3
  become: true